"""added foreign key and relationships

Revision ID: 289a171fd4ff
Revises: 80e7f447d5c9
Create Date: 2022-04-28 20:41:12.724958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289a171fd4ff'
down_revision = '80e7f447d5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###
